import { ADD_REVENUE } from "../Actions/RevenueTranAction";

let initialState = [
{saleReference: "L76ZH", saleDate: "2020-01-02", pmtMode: "Cash Payment", saleAmount: "962", saleDescription: "JMS ORGANIC STYLET OIL 15", customer : "Olga Navarro"},
{saleReference: "BFKLT", saleDate: "2020-01-02", pmtMode: "Mobile Money", saleAmount: "276", saleDescription: "TECNOKEL AMINO MG 1LT", customer : "Illana Parker"},
{saleReference: "F1O2U", saleDate: "2020-01-02", pmtMode: "Bank Transfer", saleAmount: "2897", saleDescription: "CONTROLPHYT PK 20LT", customer : "Emily Buchanan"},
{saleReference: "Z254M", saleDate: "2020-01-02", pmtMode: "Bank Transfer", saleAmount: "395", saleDescription: "TECNOKEL AMINO MG 1LT", customer : "Mia Sparks"},
{saleReference: "CQVMX", saleDate: "2020-01-02", pmtMode: "Cash Payment", saleAmount: "395", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Hanna Barnett"},
{saleReference: "76OL9", saleDate: "2020-01-02", pmtMode: "Bank Transfer", saleAmount: "1234", saleDescription: "JMS ORGANIC STYLET OIL 15", customer : "Lael Sparks"},
{saleReference: "I13M7", saleDate: "2020-01-02", pmtMode: "Mobile Money", saleAmount: "230", saleDescription: "TECNOKEL AMINO MG 1LT", customer : "Grady Calhoun"},
{saleReference: "CP32W", saleDate: "2020-01-02", pmtMode: "Cash Payment", saleAmount: "3973", saleDescription: "ESEREWURA GLYPHOSATE 20LT", customer : "Ray Gutierrez"},
{saleReference: "EUYL3", saleDate: "2020-01-02", pmtMode: "Cash Payment", saleAmount: "218", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Tashya Wallace"},
{saleReference: "LH6A6", saleDate: "2020-01-02", pmtMode: "Cash Payment", saleAmount: "124", saleDescription: "JMS ORGANIC STYLET OIL 5LT", customer : "Ruby Love"},
{saleReference: "T93BR", saleDate: "2020-01-02", pmtMode: "Bank Transfer", saleAmount: "4798", saleDescription: "TECNOKEL AMINO MG 1LT", customer : "Armand Greer"},
{saleReference: "JZ71Y", saleDate: "2020-01-02", pmtMode: "Cash Payment", saleAmount: "230", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Dominique Mann"},
{saleReference: "C4LB3", saleDate: "2020-01-02", pmtMode: "Cash Payment", saleAmount: "3973", saleDescription: "TECNOPHYT PH 1L", customer : "Cathleen Vincent"},
{saleReference: "2KGSA", saleDate: "2020-01-02", pmtMode: "Mobile Money", saleAmount: "246", saleDescription: "TECNOKEL AMINO MG 1LT", customer : "Lois Hatfield"},
{saleReference: "91ABK", saleDate: "2020-01-02", pmtMode: "Bank Transfer", saleAmount: "204", saleDescription: "TECAMIN ALGAE 1LT", customer : "Lani Cannon"},
{saleReference: "LR9GJ", saleDate: "2020-01-02", pmtMode: "Mobile Money", saleAmount: "2897", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Mira Padilla"},
{saleReference: "T1ULB", saleDate: "2020-01-02", pmtMode: "Bank Transfer", saleAmount: "1234", saleDescription: "CONTROLPHYT CU 250ML", customer : "Gannon Gates"},
{saleReference: "B68YZ", saleDate: "2020-01-03", pmtMode: "Bank Transfer", saleAmount: "330", saleDescription: "ORIZON EC IN 200ML", customer : "Stacy Crosby"},
{saleReference: "MWTBI", saleDate: "2020-01-03", pmtMode: "Mobile Money", saleAmount: "1234", saleDescription: "TECAMIN ALGAE 1LT", customer : "Sheila Wynn"},
{saleReference: "NBM9O", saleDate: "2020-01-03", pmtMode: "Cash Payment", saleAmount: "962", saleDescription: "VICTORY 72WP - 1KG", customer : "Rebekah Roman"},
{saleReference: "G1JI1", saleDate: "2020-01-03", pmtMode: "Cash Payment", saleAmount: "218", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Kirsten Lopez"},
{saleReference: "V1K3D", saleDate: "2020-01-03", pmtMode: "Mobile Money", saleAmount: "204", saleDescription: "TECNOPHYT PH 1L", customer : "Jerome Armstrong"},
{saleReference: "Y0ZAR", saleDate: "2020-01-03", pmtMode: "Cash Payment", saleAmount: "276", saleDescription: "TRIGGER10CS 100M", customer : "Shafira Hicks"},
{saleReference: "MHQH1", saleDate: "2020-01-03", pmtMode: "Cash Payment", saleAmount: "276", saleDescription: "TECAMIN MAX 1L", customer : "Sydney Norton"},
{saleReference: "A19QL", saleDate: "2020-01-03", pmtMode: "Mobile Money", saleAmount: "109", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Molly Tucker"},
{saleReference: "XKQ3Z", saleDate: "2020-01-03", pmtMode: "Cash Payment", saleAmount: "233", saleDescription: "ORIZON EC IN 200ML", customer : "Candice Avery"},
{saleReference: "I19FU", saleDate: "2020-01-03", pmtMode: "Cash Payment", saleAmount: "3973", saleDescription: "ESEREWURA GLYPHOSATE 20LT", customer : "Kelsey Mcfadden"},
{saleReference: "EIWZX", saleDate: "2020-01-03", pmtMode: "Mobile Money", saleAmount: "261", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Christen Odom"},
{saleReference: "F46YC", saleDate: "2020-01-03", pmtMode: "Mobile Money", saleAmount: "16", saleDescription: "SEED POWER 44WS 1KILO PACK", customer : "Allegra Townsend"},
{saleReference: "2CGTD", saleDate: "2020-01-03", pmtMode: "Cash Payment", saleAmount: "9842", saleDescription: "TECAMIN MAX 500ML", customer : "Wing Zimmerman"},
{saleReference: "IH9SP", saleDate: "2020-01-03", pmtMode: "Bank Transfer", saleAmount: "124", saleDescription: "TECAMIN ALGAE 1LT", customer : "Colin Madden"},
{saleReference: "JDHP9", saleDate: "2020-01-06", pmtMode: "Mobile Money", saleAmount: "246", saleDescription: "TECAMIN ALGAE 1LT", customer : "Sonya Langley"},
{saleReference: "H9K67", saleDate: "2020-01-06", pmtMode: "Cash Payment", saleAmount: "230", saleDescription: "TECAMIN MAX 500ML", customer : "Chadwick Mueller"},
{saleReference: "8VJJU", saleDate: "2020-01-06", pmtMode: "Cash Payment", saleAmount: "330", saleDescription: "IDROL - VEG DA AGRIC FERTILIZE", customer : "Chelsea Solomon"},
{saleReference: "VRZ06", saleDate: "2020-01-06", pmtMode: "Cash Payment", saleAmount: "204", saleDescription: "JMS ORGANIC STYLET OIL 15", customer : "Justina Conrad"},
{saleReference: "90ZQT", saleDate: "2020-01-06", pmtMode: "Cash Payment", saleAmount: "102", saleDescription: "TECAMIN MAX 1L", customer : "Garrett Chen"},
{saleReference: "LCOS8", saleDate: "2020-01-06", pmtMode: "Bank Transfer", saleAmount: "246", saleDescription: "TECAMIN MAX 1LT PFJ", customer : "Virginia Whitehead"},
{saleReference: "F8NG9", saleDate: "2020-01-06", pmtMode: "Bank Transfer", saleAmount: "102", saleDescription: "TECAMIN MAX 1LT PFJ", customer : "Mira Dudley"},
{saleReference: "I4YAJ", saleDate: "2020-01-06", pmtMode: "Mobile Money", saleAmount: "218", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Kenyon Prince"},
{saleReference: "6QHPD", saleDate: "2020-01-06", pmtMode: "Cash Payment", saleAmount: "246", saleDescription: "IDROL - VEG DA AGRIC FERTILIZE", customer : "Rashad Goff"},
{saleReference: "ZOHG7", saleDate: "2020-01-06", pmtMode: "Mobile Money", saleAmount: "2897", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Tobias Lang"},
{saleReference: "6QCI1", saleDate: "2020-01-06", pmtMode: "Cash Payment", saleAmount: "72", saleDescription: "IDROL - VEG DA AGRIC FERTILIZE", customer : "Todd Wagner"},
{saleReference: "AEX9X", saleDate: "2020-01-06", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "TECNOKEL AMINO MIX 1L", customer : "Theodore Barnes"},
{saleReference: "GU7MD", saleDate: "2020-01-06", pmtMode: "Cash Payment", saleAmount: "233", saleDescription: "TRIGGER10CS 100M", customer : "Evan Glover"},
{saleReference: "TNLA7", saleDate: "2020-01-06", pmtMode: "Mobile Money", saleAmount: "230", saleDescription: "CONTROLPHYT PK 20LT", customer : "Kevin Middleton"},
{saleReference: "RZVUT", saleDate: "2020-01-06", pmtMode: "Cash Payment", saleAmount: "962", saleDescription: "VICTORY 72WP - 1KG", customer : "Amaya Peters"},
{saleReference: "9V3E1", saleDate: "2020-01-06", pmtMode: "Cash Payment", saleAmount: "299", saleDescription: "TECAMIN MAX 500ML", customer : "Nissim Hanson"},
{saleReference: "OFHZI", saleDate: "2020-01-06", pmtMode: "Bank Transfer", saleAmount: "218", saleDescription: "SEED POWER 44WS 1KILO PACK", customer : "Georgia Forbes"},
{saleReference: "SKVJC", saleDate: "2020-01-08", pmtMode: "Cash Payment", saleAmount: "444", saleDescription: "TECNOKEL AMINO MG 1LT", customer : "Merritt Johns"},
{saleReference: "ONRCM", saleDate: "2020-01-08", pmtMode: "Mobile Money", saleAmount: "246", saleDescription: "ESEREWURA GLYPHOSATE 20LT", customer : "Ramona Alexander"},
{saleReference: "GJSQH", saleDate: "2020-01-08", pmtMode: "Cash Payment", saleAmount: "102", saleDescription: "TECAMIN MAX 1LT PFJ", customer : "Preston Downs"},
{saleReference: "9Q0M8", saleDate: "2020-01-08", pmtMode: "Cash Payment", saleAmount: "167", saleDescription: "AGRI M40 FERTILIZER 250L", customer : "May Delacruz"},
{saleReference: "TX534", saleDate: "2020-01-08", pmtMode: "Mobile Money", saleAmount: "1347", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Ina Kirk"},
{saleReference: "FQ7NX", saleDate: "2020-01-08", pmtMode: "Mobile Money", saleAmount: "299", saleDescription: "JMS ORGANIC STYLET OIL 15", customer : "Katell Houston"},
{saleReference: "GU5YV", saleDate: "2020-01-08", pmtMode: "Mobile Money", saleAmount: "222", saleDescription: "TECAMIN ALGAE 1LT", customer : "Wylie Spears"},
{saleReference: "6ND42", saleDate: "2020-01-08", pmtMode: "Cash Payment", saleAmount: "204", saleDescription: "TECAMIN MAX 500ML", customer : "Malcolm Booth"},
{saleReference: "A691W", saleDate: "2020-01-08", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "TECAMIN ALGAE 1LT", customer : "Zachary Neal"},
{saleReference: "SECKM", saleDate: "2020-01-08", pmtMode: "Mobile Money", saleAmount: "444", saleDescription: "TRIGGER10CS 100M", customer : "Judith Wilkins"},
{saleReference: "3DIB2", saleDate: "2020-01-08", pmtMode: "Bank Transfer", saleAmount: "4798", saleDescription: "TRIGGER10CS 100M", customer : "Lucian Baldwin"},
{saleReference: "3F0B4", saleDate: "2020-01-08", pmtMode: "Bank Transfer", saleAmount: "204", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Chanda Brady"},
{saleReference: "DH7Y4", saleDate: "2020-01-08", pmtMode: "Cash Payment", saleAmount: "104", saleDescription: "SEED POWER 44WS 10G PACK", customer : "Delilah Moses"},
{saleReference: "B9BD7", saleDate: "2020-01-08", pmtMode: "Cash Payment", saleAmount: "9842", saleDescription: "CONTROLPHYT CU 250ML", customer : "Courtney Pace"},
{saleReference: "EVM7Z", saleDate: "2020-01-08", pmtMode: "Cash Payment", saleAmount: "276", saleDescription: "TECAMIN MAX 500ML", customer : "Wyatt Kemp"},
{saleReference: "LPNWF", saleDate: "2020-01-08", pmtMode: "Cash Payment", saleAmount: "102", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Amanda Kelly"},
{saleReference: "MMRZ8", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "246", saleDescription: "JMS ORGANIC STYLET OIL 1LT", customer : "Nora Francis"},
{saleReference: "PS42W", saleDate: "2020-01-09", pmtMode: "Mobile Money", saleAmount: "3973", saleDescription: "TECNOKEL AMINO MG 1LT", customer : "Arden Short"},
{saleReference: "GLSZR", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "246", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Iris Roth"},
{saleReference: "OH6BB", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "330", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Britanni Bentley"},
{saleReference: "06CBO", saleDate: "2020-01-09", pmtMode: "Mobile Money", saleAmount: "109", saleDescription: "TECNOPHYT PH 1L", customer : "Vincent Burris"},
{saleReference: "0XYW0", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "TECNOPHYT PH 1L", customer : "Naida Goff"},
{saleReference: "V9CPD", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "299", saleDescription: "IDROL - VEG DA AGRIC FERTILIZE", customer : "Gary Pitts"},
{saleReference: "PI06I", saleDate: "2020-01-09", pmtMode: "Bank Transfer", saleAmount: "218", saleDescription: "VICTORY 72WP - 1KG", customer : "Mara Hodges"},
{saleReference: "TLWGR", saleDate: "2020-01-09", pmtMode: "Mobile Money", saleAmount: "233", saleDescription: "TECAMIN MAX 1LT PFJ", customer : "Amy Blake"},
{saleReference: "E0HJU", saleDate: "2020-01-09", pmtMode: "Bank Transfer", saleAmount: "167", saleDescription: "AGRI M40 FERTILIZER 250L", customer : "Blythe Mccormick"},
{saleReference: "8AKPL", saleDate: "2020-01-09", pmtMode: "Bank Transfer", saleAmount: "1234", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Herman Huber"},
{saleReference: "6L1T3", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "222", saleDescription: "TECAMIN MAX 500ML", customer : "Joan Garcia"},
{saleReference: "9NVGI", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "233", saleDescription: "SEED POWER 44WS 1KILO PACK", customer : "Dexter Herrera"},
{saleReference: "C2VDU", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "3973", saleDescription: "IDROL - VEG DA AGRIC FERTILIZE", customer : "Garth Berger"},
{saleReference: "P0L90", saleDate: "2020-01-09", pmtMode: "Bank Transfer", saleAmount: "246", saleDescription: "CONTROLPHYT CU 250ML", customer : "Sean Atkins"},
{saleReference: "0FJXC", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "104", saleDescription: "IDROL - VEG DA AGRIC FERTILIZE", customer : "Mohammad Hudson"},
{saleReference: "NKU05", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "3973", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Shea Hale"},
{saleReference: "4JUFG", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "2897", saleDescription: "TECAMIN MAX 1LT PFJ", customer : "Thomas Kennedy"},
{saleReference: "3LIZC", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "204", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Melinda Price"},
{saleReference: "B1FEF", saleDate: "2020-01-09", pmtMode: "Cash Payment", saleAmount: "4798", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Slade Charles"},
{saleReference: "PZPO3", saleDate: "2020-01-10", pmtMode: "Cash Payment", saleAmount: "167", saleDescription: "CONTROLPHYT PK 1L", customer : "Shellie Sheppard"},
{saleReference: "C5L6E", saleDate: "2020-01-10", pmtMode: "Cash Payment", saleAmount: "222", saleDescription: "JMS ORGANIC STYLET OIL 15", customer : "Perry Dixon"},
{saleReference: "5STNP", saleDate: "2020-01-10", pmtMode: "Cash Payment", saleAmount: "222", saleDescription: "DIZ-PYRIFOS 480 EC 250ML", customer : "Abdul Rivas"},
{saleReference: "FG2D6", saleDate: "2020-01-10", pmtMode: "Cash Payment", saleAmount: "395", saleDescription: "TECNOKEL AMINO MIX 1L", customer : "Evan Montgomery"},
{saleReference: "M32BX", saleDate: "2020-01-10", pmtMode: "Bank Transfer", saleAmount: "1347", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Victor Shaffer"},
{saleReference: "YNXER", saleDate: "2020-01-10", pmtMode: "Mobile Money", saleAmount: "230", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Travis Craig"},
{saleReference: "RIY06", saleDate: "2020-01-10", pmtMode: "Bank Transfer", saleAmount: "962", saleDescription: "TECNOKEL AMINO MIX 1L", customer : "Belle Barton"},
{saleReference: "RKTVA", saleDate: "2020-01-13", pmtMode: "Cash Payment", saleAmount: "330", saleDescription: "TECAMIN MAX 1L", customer : "Rhiannon Powell"},
{saleReference: "6PTYH", saleDate: "2020-01-13", pmtMode: "Cash Payment", saleAmount: "299", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Oliver Strong"},
{saleReference: "IYOH9", saleDate: "2020-01-13", pmtMode: "Cash Payment", saleAmount: "1234", saleDescription: "CONTROLPHYT PK 20LT", customer : "Naomi Dalton"},
{saleReference: "SBS51", saleDate: "2020-01-13", pmtMode: "Mobile Money", saleAmount: "261", saleDescription: "ESEREWURA GLYPHOSATE 20LT", customer : "Tanek Andrews"},
{saleReference: "TMDE2", saleDate: "2020-01-13", pmtMode: "Cash Payment", saleAmount: "299", saleDescription: "SEED POWER 44WS 10G PACK", customer : "Hoyt Chavez"},
{saleReference: "T40ZS", saleDate: "2020-01-13", pmtMode: "Bank Transfer", saleAmount: "395", saleDescription: "VICTORY 72WP - 1KG", customer : "Beverly Douglas"},
{saleReference: "9KH1N", saleDate: "2020-01-13", pmtMode: "Mobile Money", saleAmount: "261", saleDescription: "TECAMIN MAX 1L", customer : "Tyrone Andrews"},
{saleReference: "SDDFG", saleDate: "2020-01-13", pmtMode: "Mobile Money", saleAmount: "2897", saleDescription: "TECNOPHYT PH 1L", customer : "Jamal Rush"},
{saleReference: "61V59", saleDate: "2020-01-14", pmtMode: "Cash Payment", saleAmount: "167", saleDescription: "VICTORY 72WP - 1KG", customer : "Jorden Blankenship"},
{saleReference: "WSMUU", saleDate: "2020-01-14", pmtMode: "Mobile Money", saleAmount: "109", saleDescription: "TRIGGER10CS 100M", customer : "Olga Navarro"},
{saleReference: "Q3YF4", saleDate: "2020-01-14", pmtMode: "Mobile Money", saleAmount: "218", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Illana Parker"},
{saleReference: "YMS2A", saleDate: "2020-01-14", pmtMode: "Cash Payment", saleAmount: "109", saleDescription: "TECNOPHYT PH 1L", customer : "Emily Buchanan"},
{saleReference: "CED7Z", saleDate: "2020-01-14", pmtMode: "Cash Payment", saleAmount: "72", saleDescription: "AGRI M40 FERTILIZER 250L", customer : "Mia Sparks"},
{saleReference: "9PGJY", saleDate: "2020-01-14", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "TECNOKEL AMINO MIX 1L", customer : "Hanna Barnett"},
{saleReference: "1QNHW", saleDate: "2020-01-15", pmtMode: "Mobile Money", saleAmount: "109", saleDescription: "VICTORY 72WP - 1KG", customer : "Lael Sparks"},
{saleReference: "UXON7", saleDate: "2020-01-15", pmtMode: "Cash Payment", saleAmount: "330", saleDescription: "SEED POWER 44WS 10G PACK", customer : "Grady Calhoun"},
{saleReference: "BFGII", saleDate: "2020-01-15", pmtMode: "Cash Payment", saleAmount: "299", saleDescription: "TECAMIN MAX 1L", customer : "Ray Gutierrez"},
{saleReference: "4T8TB", saleDate: "2020-01-15", pmtMode: "Bank Transfer", saleAmount: "9842", saleDescription: "TECAMIN MAX 500ML", customer : "Tashya Wallace"},
{saleReference: "KF3NA", saleDate: "2020-01-15", pmtMode: "Cash Payment", saleAmount: "4798", saleDescription: "AGRI M40 FERTILIZER 250L", customer : "Ruby Love"},
{saleReference: "NUACU", saleDate: "2020-01-15", pmtMode: "Cash Payment", saleAmount: "276", saleDescription: "TECAMIN MAX 500ML", customer : "Armand Greer"},
{saleReference: "K5XF6", saleDate: "2020-01-15", pmtMode: "Cash Payment", saleAmount: "395", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Dominique Mann"},
{saleReference: "DILC2", saleDate: "2020-01-15", pmtMode: "Cash Payment", saleAmount: "444", saleDescription: "ESEREWURA GLYPHOSATE 20LT", customer : "Cathleen Vincent"},
{saleReference: "C3GMK", saleDate: "2020-01-16", pmtMode: "Cash Payment", saleAmount: "167", saleDescription: "JMS ORGANIC STYLET OIL 15", customer : "Lois Hatfield"},
{saleReference: "Q7DBI", saleDate: "2020-01-16", pmtMode: "Cash Payment", saleAmount: "246", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Lani Cannon"},
{saleReference: "CHRUL", saleDate: "2020-01-16", pmtMode: "Cash Payment", saleAmount: "16", saleDescription: "DIZ-PYRIFOS 480 EC 250ML", customer : "Mira Padilla"},
{saleReference: "S1LJG", saleDate: "2020-01-16", pmtMode: "Cash Payment", saleAmount: "102", saleDescription: "DIZ-PYRIFOS 480 EC 250ML", customer : "Gannon Gates"},
{saleReference: "RF0D2", saleDate: "2020-01-16", pmtMode: "Cash Payment", saleAmount: "962", saleDescription: "JMS ORGANIC STYLET OIL 15", customer : "Stacy Crosby"},
{saleReference: "2H3ST", saleDate: "2020-01-16", pmtMode: "Bank Transfer", saleAmount: "233", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Sheila Wynn"},
{saleReference: "RISCF", saleDate: "2020-01-16", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "CONTROLPHYT PK 20LT", customer : "Rebekah Roman"},
{saleReference: "QVYSS", saleDate: "2020-01-16", pmtMode: "Cash Payment", saleAmount: "124", saleDescription: "JMS ORGANIC STYLET OIL 5LT", customer : "Kirsten Lopez"},
{saleReference: "T5ATL", saleDate: "2020-01-17", pmtMode: "Cash Payment", saleAmount: "72", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Jerome Armstrong"},
{saleReference: "9GSLN", saleDate: "2020-01-17", pmtMode: "Cash Payment", saleAmount: "230", saleDescription: "TECNOKEL AMINO MIX 1L", customer : "Shafira Hicks"},
{saleReference: "TA0U7", saleDate: "2020-01-17", pmtMode: "Mobile Money", saleAmount: "246", saleDescription: "SEED POWER 44WS 10G PACK", customer : "Sydney Norton"},
{saleReference: "7239E", saleDate: "2020-01-17", pmtMode: "Cash Payment", saleAmount: "3973", saleDescription: "VICTORY 72WP - 1KG", customer : "Molly Tucker"},
{saleReference: "Z5WN0", saleDate: "2020-01-17", pmtMode: "Cash Payment", saleAmount: "2897", saleDescription: "TECNOKEL AMINO MIX 1L", customer : "Candice Avery"},
{saleReference: "VP0UC", saleDate: "2020-01-17", pmtMode: "Bank Transfer", saleAmount: "1234", saleDescription: "TECNOPHYT PH 1L", customer : "Kelsey Mcfadden"},
{saleReference: "P3NFU", saleDate: "2020-01-17", pmtMode: "Bank Transfer", saleAmount: "230", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Christen Odom"},
{saleReference: "V3AM8", saleDate: "2020-01-17", pmtMode: "Cash Payment", saleAmount: "109", saleDescription: "JMS ORGANIC STYLET OIL 15", customer : "Allegra Townsend"},
{saleReference: "5BZDN", saleDate: "2020-01-17", pmtMode: "Mobile Money", saleAmount: "1234", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Wing Zimmerman"},
{saleReference: "Y9RHX", saleDate: "2020-01-20", pmtMode: "Bank Transfer", saleAmount: "246", saleDescription: "ESEREWURA GLYPHOSATE 20LT", customer : "Colin Madden"},
{saleReference: "95S3N", saleDate: "2020-01-20", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "SEED POWER 44WS 1KILO PACK", customer : "Sonya Langley"},
{saleReference: "U84DS", saleDate: "2020-01-20", pmtMode: "Cash Payment", saleAmount: "3973", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Chadwick Mueller"},
{saleReference: "9GVQN", saleDate: "2020-01-20", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "ORIZON EC IN 200ML", customer : "Chelsea Solomon"},
{saleReference: "K1LLY", saleDate: "2020-01-20", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "CONTROLPHYT PK 1L", customer : "Justina Conrad"},
{saleReference: "V7PV0", saleDate: "2020-01-20", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "DIZ-PYRIFOS 480 EC 250ML", customer : "Garrett Chen"},
{saleReference: "7U6WA", saleDate: "2020-01-20", pmtMode: "Cash Payment", saleAmount: "1347", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Virginia Whitehead"},
{saleReference: "P75YK", saleDate: "2020-01-20", pmtMode: "Mobile Money", saleAmount: "233", saleDescription: "TECAMIN MAX 1L", customer : "Mira Dudley"},
{saleReference: "OY6XC", saleDate: "2020-01-20", pmtMode: "Cash Payment", saleAmount: "204", saleDescription: "TECAMIN MAX 1L", customer : "Kenyon Prince"},
{saleReference: "5S7L9", saleDate: "2020-01-20", pmtMode: "Mobile Money", saleAmount: "962", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Rashad Goff"},
{saleReference: "0DF56", saleDate: "2020-01-20", pmtMode: "Mobile Money", saleAmount: "222", saleDescription: "CONTROLPHYT CU 250ML", customer : "Tobias Lang"},
{saleReference: "4LCNI", saleDate: "2020-01-20", pmtMode: "Mobile Money", saleAmount: "233", saleDescription: "CONTROLPHYT CU 250ML", customer : "Todd Wagner"},
{saleReference: "HNS8R", saleDate: "2020-01-20", pmtMode: "Cash Payment", saleAmount: "104", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Theodore Barnes"},
{saleReference: "C0UHB", saleDate: "2020-01-20", pmtMode: "Bank Transfer", saleAmount: "2897", saleDescription: "SEED POWER 44WS 10G PACK", customer : "Evan Glover"},
{saleReference: "8JTY4", saleDate: "2020-01-20", pmtMode: "Cash Payment", saleAmount: "102", saleDescription: "TECNOKEL AMINO MIX 1L", customer : "Kevin Middleton"},
{saleReference: "WEEJ2", saleDate: "2020-01-21", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "JMS ORGANIC STYLET OIL 15", customer : "Amaya Peters"},
{saleReference: "KV3WM", saleDate: "2020-01-21", pmtMode: "Bank Transfer", saleAmount: "102", saleDescription: "TRIGGER10CS 100M", customer : "Nissim Hanson"},
{saleReference: "4K6AT", saleDate: "2020-01-21", pmtMode: "Cash Payment", saleAmount: "276", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Georgia Forbes"},
{saleReference: "16DNP", saleDate: "2020-01-21", pmtMode: "Bank Transfer", saleAmount: "261", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Merritt Johns"},
{saleReference: "PBDPZ", saleDate: "2020-01-21", pmtMode: "Bank Transfer", saleAmount: "444", saleDescription: "SEED POWER 44WS 10G PACK", customer : "Ramona Alexander"},
{saleReference: "30LX5", saleDate: "2020-01-21", pmtMode: "Cash Payment", saleAmount: "246", saleDescription: "IDROL - VEG DA AGRIC FERTILIZE", customer : "Preston Downs"},
{saleReference: "JDPWZ", saleDate: "2020-01-21", pmtMode: "Cash Payment", saleAmount: "233", saleDescription: "IDROL - VEG DA AGRIC FERTILIZE", customer : "May Delacruz"},
{saleReference: "TJKDD", saleDate: "2020-01-21", pmtMode: "Cash Payment", saleAmount: "109", saleDescription: "ESEREWURA GLYPHOSATE 20LT", customer : "Ina Kirk"},
{saleReference: "TPEGC", saleDate: "2020-01-22", pmtMode: "Cash Payment", saleAmount: "72", saleDescription: "TECNOPHYT PH 1L", customer : "Katell Houston"},
{saleReference: "PMRF3", saleDate: "2020-01-22", pmtMode: "Mobile Money", saleAmount: "218", saleDescription: "SEED POWER 44WS 1KILO PACK", customer : "Wylie Spears"},
{saleReference: "5UWZD", saleDate: "2020-01-22", pmtMode: "Cash Payment", saleAmount: "167", saleDescription: "TECNOKEL AMINO MIX 1L", customer : "Malcolm Booth"},
{saleReference: "HRC6C", saleDate: "2020-01-22", pmtMode: "Cash Payment", saleAmount: "222", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Zachary Neal"},
{saleReference: "5FDHE", saleDate: "2020-01-22", pmtMode: "Cash Payment", saleAmount: "395", saleDescription: "TRIGGER10CS 100M", customer : "Judith Wilkins"},
{saleReference: "I8CCC", saleDate: "2020-01-22", pmtMode: "Cash Payment", saleAmount: "167", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Lucian Baldwin"},
{saleReference: "FXW2E", saleDate: "2020-01-22", pmtMode: "Cash Payment", saleAmount: "395", saleDescription: "CONTROLPHYT PK 1L", customer : "Chanda Brady"},
{saleReference: "GZZXR", saleDate: "2020-01-22", pmtMode: "Cash Payment", saleAmount: "1347", saleDescription: "DIZ-PYRIFOS 480 EC 250ML", customer : "Delilah Moses"},
{saleReference: "6S8SJ", saleDate: "2020-01-22", pmtMode: "Mobile Money", saleAmount: "104", saleDescription: "AGRI M40 FERTILIZER 1000L", customer : "Courtney Pace"},
{saleReference: "AHHYP", saleDate: "2020-01-22", pmtMode: "Mobile Money", saleAmount: "109", saleDescription: "JMS ORGANIC STYLET OIL 1LT", customer : "Wyatt Kemp"},
{saleReference: "SGGNM", saleDate: "2020-01-22", pmtMode: "Cash Payment", saleAmount: "218", saleDescription: "TECNOPHYT PH 1L", customer : "Amanda Kelly"},
{saleReference: "QPA9N", saleDate: "2020-01-23", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "AGRI M40 FERTILIZER 1000L", customer : "Nora Francis"},
{saleReference: "P57QL", saleDate: "2020-01-23", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "SEED POWER 44WS 1KILO PACK", customer : "Arden Short"},
{saleReference: "PUH7X", saleDate: "2020-01-23", pmtMode: "Cash Payment", saleAmount: "72", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Iris Roth"},
{saleReference: "D6426", saleDate: "2020-01-23", pmtMode: "Bank Transfer", saleAmount: "218", saleDescription: "TECAMIN MAX 500ML", customer : "Britanni Bentley"},
{saleReference: "Y5218", saleDate: "2020-01-23", pmtMode: "Mobile Money", saleAmount: "222", saleDescription: "SEED POWER 44WS 1KILO PACK", customer : "Vincent Burris"},
{saleReference: "A5JFD", saleDate: "2020-01-23", pmtMode: "Mobile Money", saleAmount: "222", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Naida Goff"},
{saleReference: "BKJTX", saleDate: "2020-01-23", pmtMode: "Cash Payment", saleAmount: "222", saleDescription: "JMS ORGANIC STYLET OIL 15", customer : "Gary Pitts"},
{saleReference: "C10GF", saleDate: "2020-01-24", pmtMode: "Mobile Money", saleAmount: "1347", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Mara Hodges"},
{saleReference: "1MVSW", saleDate: "2020-01-24", pmtMode: "Cash Payment", saleAmount: "222", saleDescription: "DIZ-PYRIFOS 480 EC 250ML", customer : "Amy Blake"},
{saleReference: "8JUV2", saleDate: "2020-01-24", pmtMode: "Mobile Money", saleAmount: "261", saleDescription: "TECAMIN MAX 500ML", customer : "Blythe Mccormick"},
{saleReference: "R8K7Q", saleDate: "2020-01-24", pmtMode: "Cash Payment", saleAmount: "222", saleDescription: "TECAMIN MAX 1LT PFJ", customer : "Herman Huber"},
{saleReference: "91WDF", saleDate: "2020-01-24", pmtMode: "Cash Payment", saleAmount: "124", saleDescription: "SEED POWER 44WS 10G PACK", customer : "Joan Garcia"},
{saleReference: "JNYUC", saleDate: "2020-01-24", pmtMode: "Cash Payment", saleAmount: "962", saleDescription: "CONTROLPHYT PK 20LT", customer : "Dexter Herrera"},
{saleReference: "YCLE1", saleDate: "2020-01-24", pmtMode: "Mobile Money", saleAmount: "4798", saleDescription: "JMS ORGANIC STYLET OIL 1LT", customer : "Garth Berger"},
{saleReference: "F8J5K", saleDate: "2020-01-24", pmtMode: "Cash Payment", saleAmount: "167", saleDescription: "ORIZON EC IN 200ML", customer : "Sean Atkins"},
{saleReference: "91ZUZ", saleDate: "2020-01-24", pmtMode: "Cash Payment", saleAmount: "330", saleDescription: "IDROL - VEG DA AGRIC FERTILIZE", customer : "Mohammad Hudson"},
{saleReference: "TKTZ0", saleDate: "2020-01-24", pmtMode: "Cash Payment", saleAmount: "1234", saleDescription: "SEED POWER 44WS 1KILO PACK", customer : "Shea Hale"},
{saleReference: "K9CU8", saleDate: "2020-01-24", pmtMode: "Bank Transfer", saleAmount: "395", saleDescription: "CONTROLPHYT PK 1L", customer : "Thomas Kennedy"},
{saleReference: "5JM0D", saleDate: "2020-01-24", pmtMode: "Cash Payment", saleAmount: "218", saleDescription: "SEED POWER 44WS 10G PACK", customer : "Melinda Price"},
{saleReference: "PUZ0G", saleDate: "2020-01-27", pmtMode: "Cash Payment", saleAmount: "246", saleDescription: "TECAMIN MAX 1LT PFJ", customer : "Slade Charles"},
{saleReference: "6P27L", saleDate: "2020-01-27", pmtMode: "Cash Payment", saleAmount: "1347", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Shellie Sheppard"},
{saleReference: "789HQ", saleDate: "2020-01-27", pmtMode: "Cash Payment", saleAmount: "330", saleDescription: "TECAMIN MAX 500ML", customer : "Perry Dixon"},
{saleReference: "GNMBP", saleDate: "2020-01-27", pmtMode: "Cash Payment", saleAmount: "962", saleDescription: "TECNOPHYT PH 1L", customer : "Abdul Rivas"},
{saleReference: "E6638", saleDate: "2020-01-27", pmtMode: "Bank Transfer", saleAmount: "9842", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Evan Montgomery"},
{saleReference: "9C0HT", saleDate: "2020-01-27", pmtMode: "Mobile Money", saleAmount: "395", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Victor Shaffer"},
{saleReference: "VMV7J", saleDate: "2020-01-27", pmtMode: "Cash Payment", saleAmount: "395", saleDescription: "TECAMIN ALGAE 1LT", customer : "Travis Craig"},
{saleReference: "CMWG1", saleDate: "2020-01-27", pmtMode: "Mobile Money", saleAmount: "16", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Belle Barton"},
{saleReference: "EN01L", saleDate: "2020-01-28", pmtMode: "Cash Payment", saleAmount: "330", saleDescription: "TRIGGER10CS 100M", customer : "Rhiannon Powell"},
{saleReference: "ZZ5A4", saleDate: "2020-01-28", pmtMode: "Cash Payment", saleAmount: "1347", saleDescription: "TECNOPHYT PH 1L", customer : "Oliver Strong"},
{saleReference: "3UYA7", saleDate: "2020-01-28", pmtMode: "Cash Payment", saleAmount: "4798", saleDescription: "ESEREWURA GLYPHOSATE 20LT", customer : "Naomi Dalton"},
{saleReference: "2C6UU", saleDate: "2020-01-28", pmtMode: "Mobile Money", saleAmount: "299", saleDescription: "VICTORY 72WP - 1KG", customer : "Tanek Andrews"},
{saleReference: "1N87K", saleDate: "2020-01-28", pmtMode: "Cash Payment", saleAmount: "16", saleDescription: "CONTROLPHYT CU 250ML", customer : "Hoyt Chavez"},
{saleReference: "H5BQ7", saleDate: "2020-01-28", pmtMode: "Bank Transfer", saleAmount: "204", saleDescription: "DIZ-PYRIFOS 480 EC 250ML", customer : "Beverly Douglas"},
{saleReference: "ZZ6V3", saleDate: "2020-01-28", pmtMode: "Bank Transfer", saleAmount: "102", saleDescription: "AGRI M40 FERTILIZER 250L", customer : "Tyrone Andrews"},
{saleReference: "T4T3X", saleDate: "2020-01-28", pmtMode: "Bank Transfer", saleAmount: "204", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Jamal Rush"},
{saleReference: "W1VXA", saleDate: "2020-01-28", pmtMode: "Mobile Money", saleAmount: "3973", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Jorden Blankenship"},
{saleReference: "CGTYK", saleDate: "2020-01-28", pmtMode: "Bank Transfer", saleAmount: "444", saleDescription: "CONTROLPHYT PK 1L", customer : "Olga Navarro"},
{saleReference: "6L591", saleDate: "2020-01-28", pmtMode: "Bank Transfer", saleAmount: "246", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Illana Parker"},
{saleReference: "7IR3L", saleDate: "2020-01-28", pmtMode: "Mobile Money", saleAmount: "9842", saleDescription: "TRIGGER10CS 100M", customer : "Emily Buchanan"},
{saleReference: "VO423", saleDate: "2020-01-28", pmtMode: "Cash Payment", saleAmount: "246", saleDescription: "TECNOKEL AMINO MG 1LT", customer : "Mia Sparks"},
{saleReference: "BHJ8O", saleDate: "2020-01-28", pmtMode: "Cash Payment", saleAmount: "2897", saleDescription: "TECAMIN MAX 1L", customer : "Hanna Barnett"},
{saleReference: "PYKR9", saleDate: "2020-01-28", pmtMode: "Cash Payment", saleAmount: "276", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Lael Sparks"},
{saleReference: "37T9U", saleDate: "2020-01-28", pmtMode: "Bank Transfer", saleAmount: "444", saleDescription: "ORIZON EC IN 200ML", customer : "Grady Calhoun"},
{saleReference: "CRFS7", saleDate: "2020-01-29", pmtMode: "Bank Transfer", saleAmount: "2897", saleDescription: "VICTORY 72WP - 1KG", customer : "Ray Gutierrez"},
{saleReference: "510NC", saleDate: "2020-01-29", pmtMode: "Cash Payment", saleAmount: "3973", saleDescription: "TECNOPHYT PH 1L", customer : "Tashya Wallace"},
{saleReference: "J2QY6", saleDate: "2020-01-29", pmtMode: "Cash Payment", saleAmount: "230", saleDescription: "TRIGGER10CS 100M", customer : "Ruby Love"},
{saleReference: "0ID01", saleDate: "2020-01-29", pmtMode: "Cash Payment", saleAmount: "3973", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Armand Greer"},
{saleReference: "WDHY0", saleDate: "2020-01-29", pmtMode: "Cash Payment", saleAmount: "72", saleDescription: "AGRI M40 FERTILIZER 250L", customer : "Dominique Mann"},
{saleReference: "0ZQTR", saleDate: "2020-01-29", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Cathleen Vincent"},
{saleReference: "R7XZM", saleDate: "2020-01-29", pmtMode: "Cash Payment", saleAmount: "3973", saleDescription: "CONTROLPHYT PK 1L", customer : "Lois Hatfield"},
{saleReference: "KGRFW", saleDate: "2020-01-29", pmtMode: "Cash Payment", saleAmount: "16", saleDescription: "TECAMIN ALGAE 1LT", customer : "Lani Cannon"},
{saleReference: "MCZO7", saleDate: "2020-01-29", pmtMode: "Bank Transfer", saleAmount: "102", saleDescription: "AGRI M40 FERTILIZER 250L", customer : "Mira Padilla"},
{saleReference: "XIWE1", saleDate: "2020-01-29", pmtMode: "Mobile Money", saleAmount: "167", saleDescription: "TRIGGER10CS 100M", customer : "Gannon Gates"},
{saleReference: "FS1WL", saleDate: "2020-01-29", pmtMode: "Mobile Money", saleAmount: "246", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Stacy Crosby"},
{saleReference: "2B9S1", saleDate: "2020-01-29", pmtMode: "Cash Payment", saleAmount: "962", saleDescription: "CONTROLPHYT PK 1L", customer : "Sheila Wynn"},
{saleReference: "ZAZ15", saleDate: "2020-01-29", pmtMode: "Bank Transfer", saleAmount: "4798", saleDescription: "SEED POWER 44WS 10G PACK", customer : "Rebekah Roman"},
{saleReference: "SIWKT", saleDate: "2020-01-29", pmtMode: "Bank Transfer", saleAmount: "124", saleDescription: "TRIGGER10CS 100M", customer : "Kirsten Lopez"},
{saleReference: "ZFGZP", saleDate: "2020-01-31", pmtMode: "Bank Transfer", saleAmount: "109", saleDescription: "VICTORY 72WP - 1KG", customer : "Jerome Armstrong"},
{saleReference: "RQ2G1", saleDate: "2020-01-31", pmtMode: "Cash Payment", saleAmount: "109", saleDescription: "TECAMIN MAX 1L", customer : "Shafira Hicks"},
{saleReference: "WHWYV", saleDate: "2020-01-31", pmtMode: "Cash Payment", saleAmount: "261", saleDescription: "SEED POWER 44WS 1KILO PACK", customer : "Sydney Norton"},
{saleReference: "06JLN", saleDate: "2020-01-31", pmtMode: "Cash Payment", saleAmount: "299", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Molly Tucker"},
{saleReference: "6840A", saleDate: "2020-01-31", pmtMode: "Cash Payment", saleAmount: "1347", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Candice Avery"},
{saleReference: "8VBPQ", saleDate: "2020-01-31", pmtMode: "Cash Payment", saleAmount: "167", saleDescription: "TRIGGER10CS 100M", customer : "Kelsey Mcfadden"},
{saleReference: "081F7", saleDate: "2020-01-31", pmtMode: "Cash Payment", saleAmount: "230", saleDescription: "TECAMIN MAX 1L", customer : "Christen Odom"},
{saleReference: "UEXZR", saleDate: "2020-01-31", pmtMode: "Cash Payment", saleAmount: "1347", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Allegra Townsend"},
{saleReference: "OWLAO", saleDate: "2020-01-31", pmtMode: "Cash Payment", saleAmount: "1234", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Wing Zimmerman"},
{saleReference: "POEFH", saleDate: "2020-01-31", pmtMode: "Bank Transfer", saleAmount: "72", saleDescription: "TECAMIN MAX 500ML", customer : "Colin Madden"},
{saleReference: "TO3YU", saleDate: "2020-01-31", pmtMode: "Mobile Money", saleAmount: "2897", saleDescription: "JMS ORGANIC STYLET OIL 5LT", customer : "Sonya Langley"},
{saleReference: "EG95A", saleDate: "2020-02-03", pmtMode: "Mobile Money", saleAmount: "330", saleDescription: "JMS ORGANIC STYLET OIL 1LT", customer : "Chadwick Mueller"},
{saleReference: "GIPD3", saleDate: "2020-02-03", pmtMode: "Cash Payment", saleAmount: "9842", saleDescription: "IDROL - VEG DA AGRIC FERTILIZE", customer : "Chelsea Solomon"},
{saleReference: "B2Z0O", saleDate: "2020-02-03", pmtMode: "Cash Payment", saleAmount: "204", saleDescription: "TRIGGER10CS 100M", customer : "Justina Conrad"},
{saleReference: "EZP65", saleDate: "2020-02-03", pmtMode: "Mobile Money", saleAmount: "230", saleDescription: "TECAMIN ALGAE 1LT", customer : "Garrett Chen"},
{saleReference: "O2F2I", saleDate: "2020-02-03", pmtMode: "Cash Payment", saleAmount: "246", saleDescription: "TECAMIN MAX 500ML", customer : "Virginia Whitehead"},
{saleReference: "C650B", saleDate: "2020-02-03", pmtMode: "Mobile Money", saleAmount: "222", saleDescription: "SEED POWER 44WS 10G PACK", customer : "Mira Dudley"},
{saleReference: "U4K0T", saleDate: "2020-02-03", pmtMode: "Cash Payment", saleAmount: "2897", saleDescription: "VICTORY 72WP - 1KG", customer : "Kenyon Prince"},
{saleReference: "DD469", saleDate: "2020-02-03", pmtMode: "Bank Transfer", saleAmount: "1347", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Rashad Goff"},
{saleReference: "D6X98", saleDate: "2020-02-03", pmtMode: "Mobile Money", saleAmount: "218", saleDescription: "AGRI M40 FERTILIZER 1000L", customer : "Tobias Lang"},
{saleReference: "1CB7T", saleDate: "2020-02-03", pmtMode: "Cash Payment", saleAmount: "1347", saleDescription: "AGRI M40 FERTILIZER 250L", customer : "Todd Wagner"},
{saleReference: "58G8M", saleDate: "2020-02-03", pmtMode: "Mobile Money", saleAmount: "167", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Theodore Barnes"},
{saleReference: "WYQA7", saleDate: "2020-02-04", pmtMode: "Bank Transfer", saleAmount: "222", saleDescription: "ORIZON EC IN 200ML", customer : "Evan Glover"},
{saleReference: "JDKSR", saleDate: "2020-02-04", pmtMode: "Cash Payment", saleAmount: "444", saleDescription: "SEED POWER 44WS 1KILO PACK", customer : "Kevin Middleton"},
{saleReference: "AK8QL", saleDate: "2020-02-04", pmtMode: "Bank Transfer", saleAmount: "276", saleDescription: "JMS ORGANIC STYLET OIL 1LT", customer : "Amaya Peters"},
{saleReference: "3QP6E", saleDate: "2020-02-04", pmtMode: "Cash Payment", saleAmount: "299", saleDescription: "IDROL - VEG DA AGRIC FERTILIZE", customer : "Nissim Hanson"},
{saleReference: "MFEEY", saleDate: "2020-02-04", pmtMode: "Cash Payment", saleAmount: "16", saleDescription: "TECAMIN MAX 1L", customer : "Georgia Forbes"},
{saleReference: "WEACS", saleDate: "2020-02-04", pmtMode: "Mobile Money", saleAmount: "1347", saleDescription: "TECAMIN MAX 1LT PFJ", customer : "Merritt Johns"},
{saleReference: "FI65G", saleDate: "2020-02-04", pmtMode: "Mobile Money", saleAmount: "3973", saleDescription: "TECNOPHYT PH 1L", customer : "Ramona Alexander"},
{saleReference: "G2D7B", saleDate: "2020-02-04", pmtMode: "Bank Transfer", saleAmount: "261", saleDescription: "TECAMIN MAX 500ML", customer : "Preston Downs"},
{saleReference: "GP1NW", saleDate: "2020-02-04", pmtMode: "Cash Payment", saleAmount: "222", saleDescription: "JMS ORGANIC STYLET OIL 1LT", customer : "May Delacruz"},
{saleReference: "NG9K8", saleDate: "2020-02-04", pmtMode: "Cash Payment", saleAmount: "1347", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Ina Kirk"},
{saleReference: "NH7GT", saleDate: "2020-02-04", pmtMode: "Cash Payment", saleAmount: "276", saleDescription: "TRIGGER10CS 100M", customer : "Katell Houston"},
{saleReference: "0IIGW", saleDate: "2020-02-04", pmtMode: "Bank Transfer", saleAmount: "276", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Wylie Spears"},
{saleReference: "IFLV4", saleDate: "2020-02-05", pmtMode: "Bank Transfer", saleAmount: "2897", saleDescription: "TECAMIN ALGAE 1LT", customer : "Malcolm Booth"},
{saleReference: "FVEZ2", saleDate: "2020-02-05", pmtMode: "Cash Payment", saleAmount: "230", saleDescription: "JMS ORGANIC STYLET OIL 1LT", customer : "Zachary Neal"},
{saleReference: "8VFX8", saleDate: "2020-02-05", pmtMode: "Cash Payment", saleAmount: "3973", saleDescription: "TECAMIN MAX 1LT PFJ", customer : "Judith Wilkins"},
{saleReference: "P9R75", saleDate: "2020-02-05", pmtMode: "Cash Payment", saleAmount: "330", saleDescription: "TRIGGER10CS 100M", customer : "Lucian Baldwin"},
{saleReference: "8YOQN", saleDate: "2020-02-05", pmtMode: "Cash Payment", saleAmount: "299", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Chanda Brady"},
{saleReference: "RMPT0", saleDate: "2020-02-05", pmtMode: "Cash Payment", saleAmount: "4798", saleDescription: "JMS ORGANIC STYLET OIL 15", customer : "Delilah Moses"},
{saleReference: "SZARF", saleDate: "2020-02-05", pmtMode: "Bank Transfer", saleAmount: "261", saleDescription: "AGRI M40 FERTILIZER 250L", customer : "Courtney Pace"},
{saleReference: "1W19Z", saleDate: "2020-02-05", pmtMode: "Cash Payment", saleAmount: "230", saleDescription: "ESEREWURA GLYPHOSATE 20LT", customer : "Wyatt Kemp"},
{saleReference: "B4FO3", saleDate: "2020-02-05", pmtMode: "Cash Payment", saleAmount: "124", saleDescription: "TECAMIN MAX 1L", customer : "Amanda Kelly"},
{saleReference: "X6LZF", saleDate: "2020-02-05", pmtMode: "Cash Payment", saleAmount: "16", saleDescription: "TECAMIN MAX 1LT PFJ", customer : "Nora Francis"},
{saleReference: "WA6AV", saleDate: "2020-02-06", pmtMode: "Mobile Money", saleAmount: "72", saleDescription: "MECTIN (ABAMECTIN) 100ML BOTTL", customer : "Arden Short"},
{saleReference: "9SA9N", saleDate: "2020-02-06", pmtMode: "Bank Transfer", saleAmount: "4798", saleDescription: "AGRI M40 FERTILIZER 1000L", customer : "Iris Roth"},
{saleReference: "BWL5D", saleDate: "2020-02-06", pmtMode: "Mobile Money", saleAmount: "299", saleDescription: "ESEREWURA GLYPHOSATE 20LT", customer : "Britanni Bentley"},
{saleReference: "ZH5C7", saleDate: "2020-02-06", pmtMode: "Cash Payment", saleAmount: "330", saleDescription: "SEED POWER 44WS 1KILO PACK", customer : "Vincent Burris"},
{saleReference: "417W7", saleDate: "2020-02-06", pmtMode: "Bank Transfer", saleAmount: "395", saleDescription: "AGRI M40 FERTILIZER 1000L", customer : "Naida Goff"},
{saleReference: "EZGWE", saleDate: "2020-02-10", pmtMode: "Mobile Money", saleAmount: "330", saleDescription: "AGRI M40 FERTILIZER 250L", customer : "Gary Pitts"},
{saleReference: "3CTTZ", saleDate: "2020-02-10", pmtMode: "Cash Payment", saleAmount: "395", saleDescription: "JMS ORGANIC STYLET OIL 1LT", customer : "Mara Hodges"},
{saleReference: "GYJOL", saleDate: "2020-02-10", pmtMode: "Mobile Money", saleAmount: "109", saleDescription: "TECAMIN MAX 1LT PFJ", customer : "Amy Blake"},
{saleReference: "C1O5O", saleDate: "2020-02-10", pmtMode: "Cash Payment", saleAmount: "222", saleDescription: "TRIGGER10CS 100M", customer : "Blythe Mccormick"},
{saleReference: "9OIDX", saleDate: "2020-02-10", pmtMode: "Cash Payment", saleAmount: "204", saleDescription: "AGRI M40 FERTILIZER 1000L", customer : "Herman Huber"},
{saleReference: "RGCZ4", saleDate: "2020-02-10", pmtMode: "Cash Payment", saleAmount: "444", saleDescription: "CONTROLPHYT CU 250ML", customer : "Joan Garcia"},
{saleReference: "J389K", saleDate: "2020-02-10", pmtMode: "Bank Transfer", saleAmount: "222", saleDescription: "TECNOKEL AMINO FE 1LT", customer : "Dexter Herrera"},
{saleReference: "H2AP2", saleDate: "2020-02-10", pmtMode: "Mobile Money", saleAmount: "109", saleDescription: "ORIZON EC IN 200ML", customer : "Garth Berger"},
{saleReference: "U4EJD", saleDate: "2020-02-10", pmtMode: "Cash Payment", saleAmount: "102", saleDescription: "TECNOKEL AMINO MIX 1L", customer : "Sean Atkins"},
{saleReference: "YDDKM", saleDate: "2020-02-10", pmtMode: "Cash Payment", saleAmount: "1347", saleDescription: "VICTORY 72WP - 1KG", customer : "Mohammad Hudson"},
{saleReference: "7D66Z", saleDate: "2020-02-11", pmtMode: "Mobile Money", saleAmount: "222", saleDescription: "DIZ-PYRIFOS 480 EC 1 LT", customer : "Shea Hale"},
{saleReference: "L62HG", saleDate: "2020-02-11", pmtMode: "Cash Payment", saleAmount: "218", saleDescription: "TECNOKEL AMINO CAB 1LT", customer : "Thomas Kennedy"},
{saleReference: "0BEIF", saleDate: "2020-02-11", pmtMode: "Bank Transfer", saleAmount: "261", saleDescription: "ESEREWURA GLYPHOSATE 20LT", customer : "Melinda Price"},
{saleReference: "42DZV", saleDate: "2020-02-11", pmtMode: "Mobile Money", saleAmount: "104", saleDescription: "DIZ-PYRIFOS 480 EC 250ML", customer : "Slade Charles"},


]

const RevTranReducer =(state = initialState, action)=>{
    switch(action.type){
        case ADD_REVENUE:
            
            return (
                [...state, action.payload]
                )
    default:
        return state
    }
}

export default RevTranReducer
